server:
  port: 8082
  servlet:
    #不能配置为/，否则认证通过后不能重定向回客户端的访问地址
    context-path: /server


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

oauth2:
  server:
    url: https://oauth.inyaa.cn
    logout: ${oauth2.server.url}/logout #可以实现单点登录，不能实现单点登出
    client-id: postman # 2 客户端ID
    client-secret: postman # 3 客户端密码
  resource:
    url: https://resource.inyaa.cn

spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  application:
    name: inyaa-web
  datasource:
    url: jdbc:mysql://122.51.60.92:3306/inyaa?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    database: 0
    host: 122.51.60.92
    port: 6379
  security:
    oauth2:
      client:
        registration:
          inyaa: # 1 注册客户端名称，随意指定，但是要与provider的配置相一致
            client-id: postman # 2 客户端ID
            client-secret: postman # 3 客户端密码
            authorization-grant-type: authorization_code # 4 认证类型
            #默认重定向URI模板是{baseUrl}/login/oauth2/code/{registrationId}。
            #registrationId是ClientRegistration的唯一标识符。
            redirect-uri: https://www.inyaa.cn/server/login/oauth2/code/inyaa  # 5 回调地址，需要配置到数据表中，默认写法，注意最后的路径是注册客户端名称
            scope: any #请求范围
            client-name: 客户端1
          github:
            client-id: e6e6a9b66c052a99a288 # 2 客户端ID
            client-secret: 93129918b0aae5b8dcc41656dda70bab04e94527 # 3 客户端密码
            redirect-uri: https://www.inyaa.cn/server/login/oauth2/code/github
          qq:
            clientId: 101942482
            clientSecret: 29a108a760911901769358dc5c1c8c95
            # 在本地测试时需要配置代理将自己在qq注册的redirectUri重定向为http://localhost/api/login/oauth2/code/qq
            redirectUri: https://www.inyaa.cn/api/login/oauth2/code/qq
            authorizationGrantType: authorization_code
            # 授权码模式需要传递code、state、client_id、client_secret等参数，OAuth2AuthorizationCodeGrantRequestEntityConverter
            # 会根据当前的认证方式传递不同的参数
            clientAuthenticationMethod: post
        provider:
          inyaa:
            authorization-uri: ${oauth2.server.url}/oauth/authorize # 7 认证地址
            token-uri: ${oauth2.server.url}/oauth/token # 8 获取token地址
            user-info-uri: https://resource.inyaa.cn/userInfo # 9 获取用户信息地址，必须配置
            userNameAttribute: username # 10 指定用户信息中哪个属性是用户名称
          qq:
            authorizationUri: https://graph.qq.com/oauth2.0/authorize
            tokenUri: https://graph.qq.com/oauth2.0/token
            userInfoUri: https://graph.qq.com/user/get_user_info
            userNameAttribute: nickname
