server:
  port: 8080
spring:
  application:
    name: oauth2-auth-server
  datasource:
    url: jdbc:mysql://122.51.60.92:3306/inyaa?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:oauth2_key.pub

#springsecurity 自定义属性
security:
  #不需要验证的路径
  permitAll:
    - /redirect/**
  ignoring:
    - /webjars/**
    - /**/*.js
    - /**/*.css
    - /static/**

#自定义jwt属性信息
jwt:
  type: jks # 密钥类型：secret，jks
  #  SECRET 是签名密钥，只生成一次即可，生成方法：
  #  Key key = Keys.secretKeyFor(SignatureAlgorithm.HS512);
  #  String secretString = Encoders.BASE64.encode(key.getEncoded()); # 使用 BASE64 编码
  secret: Ayl7bn+aFwxlakekKCJiqUYguKS80bEVb7OZtd2qfZjdCbAwKxDmM6PWezGy5JIkiJfemtHNPc7Av1l+OWQSqQ== # 秘钥
  accessTokenValiditySeconds: 43200   # access_token过期时间 (秒) ,默认值12小时
  refreshTokenValiditySeconds: 2592000 # refresh_token过期时间 (秒) ,默认值30天
  jksKeyFile: classpath:oauth2_key.jks
  jksStorePassword: 123456
  jksKeyAlias: oauth2
  jksKeyPassword: 123456


#oauth2的client信息是基于内存还是基于数据库，如果不配置，默认为基于内存
oauth2:
  clients:
    config:
      jdbc: true